### PR TITLE
Update to follow standard node.js callback pattern

### PR DESCRIPTION
**Pull request by KaptainKrayola**
I really like your work but wanted it to follow the standard node.js callback(err, results) pattern.  I updated your functions to callback with that pattern.  Updated the readme as well.

### CODE REVIEW

**Comment by adcpm** [comment]
Thank you for contribution. I will merge it, but I dont get it why you wanna change to npm install?

**Comment by KaptainKrayola** [comment]
didn't mean to have you merge that.  just put that there in case you didn't merge or didn't respond so people could still npm install it.

**Comment by adcpm** [comment]
Can you remove this change of the request?

**Comment by KaptainKrayola** [comment]
i changed it back to the normal npm package

**Comment by adcpm** [comment]
Thank you i didn't know about this standard!

**Comment by KaptainKrayola** [comment]
You're welcome.  Thanks for saving me a ton of work by building this.  I do think I'll build one that talks directly to the steemd client instead of piston.rocks but this is a great start for me.

**Comment by adcpm** [comment]
Do you think steemd websocket is more legit? I could set it by default.

**Comment by KaptainKrayola** [comment]
I think it would mean not having to rely on another company / product to pull block information.  Every API call you do would have to change because the format to talk to steed is different than Piston.  

Example : 
```
self.getBlock = function(blockNum, allDone){
	self.sendMessage(['database_api', 'get_block', [blockNum]])
}
```
Maybe we can roll the calls to steemd into another module and then when creating a new Steem you can specify a "mode" or something - default to Piston but allow for steemd and then swap out the calls depending on which mode they set.

**Comment by adcpm** [comment]
Exactly, i'm interesting about how exactly steemd.com WS work. Is there a doc?
I'm now using the steemit WS to dev in local, it's using the same standard than pistol.

**Comment by adcpm** [comment]
Are you on Slack?

**Comment by KaptainKrayola** [comment]
What is the url for the steemit ws?  I was using a copy of steemd on my local machine and querying it directly over ws.  

I'm not on slack.  I'm not sure what I'm supposed to use for an email address to get signed in. - i'm on Skype as kaptainkrayola though if you want to chat

**Comment by adcpm** [comment]
Here is the Steemit WS wss://steemit.com/wstmp3

**Comment by adcpm** [comment]
I added you on Skype!

**Pull request merged**
